---
title: "p8105_hw3_jv2629"
author: "Jaclyn Verity - jv2629"
date: "October 10, 2018"
output: github_document
---

#Setup the the document for success!
```{r setup}
knitr::opts_chunk$set(echo = TRUE)
  fig.width = 6
  fig.asp = .6
  out.width = "90%"

library(tidyverse)
library(ggridges)
  
theme_set(theme_bw() + theme(legend.position = "bottom"))
```

#Problem 1
```{r}
library(p8105.datasets)

beh_risk = brfss_smart2010 %>% 
  janitor::clean_names() %>% 
  filter(topic == "Overall Health") %>% 
 rename(state = locationabbr, county = locationdesc)

beh_risk = beh_risk %>% 
  mutate(response = factor(response, levels = c("Poor", "Fair", "Good", "Very good", "Excellent"))) %>% 
  arrange(desc(response))
```

**In 2002, which states were observed at 7 locations?**
```{r first question}
beh_risk %>% 
  filter(year == 2002) %>%
  group_by(state) %>% 
  distinct(state, county) %>%  
  summarise(county = n())
```

In 2002, North Carolina, Florida, and Connecticut were observed at 7 locations. 


**Make a “spaghetti plot” that shows the number of locations in each state from 2002 to 2010.**
```{r}
spag_plot = beh_risk %>% 
  group_by(year, state) %>% 
  distinct(county, .keep_all = TRUE) %>%  
  summarise(county = n()) 

ggplot(data = spag_plot, aes(x = year , y = county, group = state, color = state)) + geom_line()

```

